In [1]:
#import pandas, numpy, and os libraries
import pandas as pd
import numpy as np
import os
path = r'C:\Users\joelf\OneDrive\Documents\CareerFoundry\4 Python\Instacart Data'

In [2]:
#1
#import ords_prior
ords_prods_merged = pd.read_pickle(os.path.join(path, 'NewDataSets', 'orders_products_combined.pkl'))
ords_prods_merged.shape

(32404859, 19)

In [3]:
ords_prods_merged.head(10)

,order_id,user_id,order_number,orders_day_of_week,order_time,days_since_prior_order,repeat_customer,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_label,busiest_day,two_busiest_days,busiest_hours
0,2539329,1,1,2,8,NaN,0,196,1,0,Soda,77,7,9.0,both,mid_range product,normal day,normal day,average orders
1,2398795,1,2,3,7,15.0,1,196,1,1,Soda,77,7,9.0,both,mid_range product,normal day,slowest day,average orders
2,473747,1,3,3,12,21.0,1,196,1,1,Soda,77,7,9.0,both,mid_range product,normal day,slowest day,average orders
3,2254736,1,4,4,7,29.0,1,196,1,1,Soda,77,7,9.0,both,mid_range product,slowest day,slowest day,average orders
4,431534,1,5,4,15,28.0,1,196,1,1,Soda,77,7,9.0,both,mid_range product,slowest day,slowest day,average orders
5,3367565,1,6,2,7,19.0,1,196,1,1,Soda,77,7,9.0,both,mid_range product,normal day,normal day,average orders
6,550135,1,7,1,9,20.0,1,196,1,1,Soda,77,7,9.0,both,mid_range product,normal day,busiest day,average orders
7,3108588,1,8,1,14,14.0,1,196,2,1,Soda,77,7,9.0,both,mid_range product,normal day,busiest day,average orders
8,2295261,1,9,1,16,0.0,1,196,4,1,Soda,77,7,9.0,both,mid_range product,normal day,busiest day,average orders
9,2550362,1,10,4,8,30.0,1,196,1,1,Soda,77,7,9.0,both,mid_range product,slowest day,slowest day,average orders

In [4]:
#2
#Find mean of order_number column when grouped by department_id
ords_prods_merged.groupby('department_id')['order_number'].mean()

department_id
1     15.457838
2     17.277920
3     17.170395
4     17.811403
5     15.215751
6     16.439806
7     17.225802
8     15.340650
9     15.895474
10    20.197148
11    16.170638
12    15.887671
13    16.583536
14    16.773669
15    16.165037
16    17.665606
17    15.694469
18    19.310397
19    17.177343
20    16.473447
21    22.902379
Name: order_number, dtype: float64

#3
For the most part the means for the whole dataset are lower. The dataset of the first 1000000 rows had users with more orders on avg
I would speculate that lower user_id numbers (included in the first 1m rows) are assigned to the oldest instacart members and older members have more time to place orders. Including the whole dataset brings in newer users with fewer orders.

In [5]:
#4a
#create max order column and pop with max number of orders for that customer to see who has the most orders
ords_prods_merged['max_order'] = ords_prods_merged.groupby(['user_id'])['order_number'].transform(np.max)
ords_prods_merged.head(15)

,order_id,user_id,order_number,orders_day_of_week,order_time,days_since_prior_order,repeat_customer,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_label,busiest_day,two_busiest_days,busiest_hours,max_order
0,2539329,1,1,2,8,NaN,0,196,1,0,Soda,77,7,9.0,both,mid_range product,normal day,normal day,average orders,10
1,2398795,1,2,3,7,15.0,1,196,1,1,Soda,77,7,9.0,both,mid_range product,normal day,slowest day,average orders,10
2,473747,1,3,3,12,21.0,1,196,1,1,Soda,77,7,9.0,both,mid_range product,normal day,slowest day,average orders,10
3,2254736,1,4,4,7,29.0,1,196,1,1,Soda,77,7,9.0,both,mid_range product,slowest day,slowest day,average orders,10
4,431534,1,5,4,15,28.0,1,196,1,1,Soda,77,7,9.0,both,mid_range product,slowest day,slowest day,average orders,10
5,3367565,1,6,2,7,19.0,1,196,1,1,Soda,77,7,9.0,both,mid_range product,normal day,normal day,average orders,10
6,550135,1,7,1,9,20.0,1,196,1,1,Soda,77,7,9.0,both,mid_range product,normal day,busiest day,average orders,10
7,3108588,1,8,1,14,14.0,1,196,2,1,Soda,77,7,9.0,both,mid_range product,normal day,busiest day,average orders,10
8,2295261,1,9,1,16,0.0,1,196,4,1,Soda,77,7,9.0,both,mid_range product,normal day,busiest day,average orders,10
9,2550362,1,10,4,8,30.0,1,196,1,1,Soda,77,7,9.0,both,mid_range product,slowest day,slowest day,average orders,10
10,2968173,15,15,1,9,7.0,1,196,2,0,Soda,77,7,9.0,both,mid_range product,normal day,busiest day,average orders,22
11,1870022,15,17,2,16,8.0,1,196,6,1,Soda,77,7,9.0,both,mid_range product,normal day,normal day,average orders,22
12,1911383,15,18,2,11,7.0,1,196,1,1,Soda,77,7,9.0,both,mid_range product,normal day,normal day,most orders,22
13,2715276,15,21,1,9,7.0,1,196,1,1,Soda,77,7,9.0,both,mid_range product,normal day,busiest day,average orders,22
14,487368,15,22,1,10,14.0,1,196,1,1,Soda,77,7,9.0,both,mid_range product,normal day,busiest day,most orders,22

In [6]:
#4b
#loyalty flags for whole dataset
ords_prods_merged.loc[ords_prods_merged['max_order'] > 40, 'loyalty_flag'] = 'Loyal Customer'
ords_prods_merged.loc[ (ords_prods_merged['max_order'] <= 40) & (ords_prods_merged['max_order'] > 10), 'loyalty_flag'] = 'Regular Customer'
ords_prods_merged.loc[ords_prods_merged['max_order'] <= 10, 'loyalty_flag'] = 'New Customer'
ords_prods_merged['loyalty_flag'].value_counts(dropna = False)

Regular Customer    15876776
Loyal Customer      10284093
New Customer         6243990
Name: loyalty_flag, dtype: int64

In [7]:
#4c
#checking to make sure flags worked
ords_prods_merged[['user_id','loyalty_flag','max_order']].head(60)

    user_id      loyalty_flag  max_order
0         1      New Customer         10
1         1      New Customer         10
2         1      New Customer         10
3         1      New Customer         10
4         1      New Customer         10
5         1      New Customer         10
6         1      New Customer         10
7         1      New Customer         10
8         1      New Customer         10
9         1      New Customer         10
10       15  Regular Customer         22
11       15  Regular Customer         22
12       15  Regular Customer         22
13       15  Regular Customer         22
14       15  Regular Customer         22
15       19      New Customer          9
16       19      New Customer          9
17       19      New Customer          9
18       21  Regular Customer         33
19       31  Regular Customer         20
20       31  Regular Customer         20
21       43  Regular Customer         11
22       43  Regular Customer         11
23       52  Regular Customer         27
24       52  Regular Customer         27
25       52  Regular Customer         27
26       52  Regular Customer         27
27       52  Regular Customer         27
28       52  Regular Customer         27
29       52  Regular Customer         27
30       52  Regular Customer         27
31       52  Regular Customer         27
32       52  Regular Customer         27
33       52  Regular Customer         27
34       52  Regular Customer         27
35       52  Regular Customer         27
36       52  Regular Customer         27
37       67  Regular Customer         24
38       67  Regular Customer         24
39       67  Regular Customer         24
40       67  Regular Customer         24
41       67  Regular Customer         24
42       67  Regular Customer         24
43       67  Regular Customer         24
44       67  Regular Customer         24
45       67  Regular Customer         24
46       67  Regular Customer         24
47       67  Regular Customer         24
48       67  Regular Customer         24
49       67  Regular Customer         24
50       67  Regular Customer         24
51       67  Regular Customer         24
52       67  Regular Customer         24
53       67  Regular Customer         24
54       67  Regular Customer         24
55       67  Regular Customer         24
56       81      New Customer          7
57       81      New Customer          7
58       82  Regular Customer         19
59       82  Regular Customer         19

In [8]:
#5
#find average price of products when grouped by loyalty flag
ords_prods_merged.groupby('loyalty_flag')['prices'].mean()

loyalty_flag
Loyal Customer      10.386336
New Customer        13.294670
Regular Customer    12.495717
Name: prices, dtype: float64

Average product price is lowest for loyal customers

In [9]:
#6
#create column with avg price for each customer
#spending flag based on avg price across orders
#   mean < 10 = low spender
#   mean >=10 = high spender
ords_prods_merged['avg_price'] = ords_prods_merged.groupby(['user_id'])['prices'].transform(np.mean)
ords_prods_merged.head(15)

,order_id,user_id,order_number,orders_day_of_week,order_time,days_since_prior_order,repeat_customer,product_id,add_to_cart_order,reordered,...,department_id,prices,_merge,price_label,busiest_day,two_busiest_days,busiest_hours,max_order,loyalty_flag,avg_price
0,2539329,1,1,2,8,NaN,0,196,1,0,...,7,9.0,both,mid_range product,normal day,normal day,average orders,10,New Customer,6.367797
1,2398795,1,2,3,7,15.0,1,196,1,1,...,7,9.0,both,mid_range product,normal day,slowest day,average orders,10,New Customer,6.367797
2,473747,1,3,3,12,21.0,1,196,1,1,...,7,9.0,both,mid_range product,normal day,slowest day,average orders,10,New Customer,6.367797
3,2254736,1,4,4,7,29.0,1,196,1,1,...,7,9.0,both,mid_range product,slowest day,slowest day,average orders,10,New Customer,6.367797
4,431534,1,5,4,15,28.0,1,196,1,1,...,7,9.0,both,mid_range product,slowest day,slowest day,average orders,10,New Customer,6.367797
5,3367565,1,6,2,7,19.0,1,196,1,1,...,7,9.0,both,mid_range product,normal day,normal day,average orders,10,New Customer,6.367797
6,550135,1,7,1,9,20.0,1,196,1,1,...,7,9.0,both,mid_range product,normal day,busiest day,average orders,10,New Customer,6.367797
7,3108588,1,8,1,14,14.0,1,196,2,1,...,7,9.0,both,mid_range product,normal day,busiest day,average orders,10,New Customer,6.367797
8,2295261,1,9,1,16,0.0,1,196,4,1,...,7,9.0,both,mid_range product,normal day,busiest day,average orders,10,New Customer,6.367797
9,2550362,1,10,4,8,30.0,1,196,1,1,...,7,9.0,both,mid_range product,slowest day,slowest day,average orders,10,New Customer,6.367797
10,2968173,15,15,1,9,7.0,1,196,2,0,...,7,9.0,both,mid_range product,normal day,busiest day,average orders,22,Regular Customer,3.980556
11,1870022,15,17,2,16,8.0,1,196,6,1,...,7,9.0,both,mid_range product,normal day,normal day,average orders,22,Regular Customer,3.980556
12,1911383,15,18,2,11,7.0,1,196,1,1,...,7,9.0,both,mid_range product,normal day,normal day,most orders,22,Regular Customer,3.980556
13,2715276,15,21,1,9,7.0,1,196,1,1,...,7,9.0,both,mid_range product,normal day,busiest day,average orders,22,Regular Customer,3.980556
14,487368,15,22,1,10,14.0,1,196,1,1,...,7,9.0,both,mid_range product,normal day,busiest day,most orders,22,Regular Customer,3.980556

In [10]:
#6 cont.
ords_prods_merged.loc[ords_prods_merged['avg_price'] < 10, 'spender_flag'] = 'Low Spender'
ords_prods_merged.loc[ords_prods_merged['avg_price'] >= 10, 'spender_flag'] = 'High Spender'
ords_prods_merged['spender_flag'].value_counts(dropna = False)

Low Spender     31770614
High Spender      634245
Name: spender_flag, dtype: int64

In [11]:
ords_prods_merged.head(50)

,order_id,user_id,order_number,orders_day_of_week,order_time,days_since_prior_order,repeat_customer,product_id,add_to_cart_order,reordered,...,prices,_merge,price_label,busiest_day,two_busiest_days,busiest_hours,max_order,loyalty_flag,avg_price,spender_flag
0,2539329,1,1,2,8,NaN,0,196,1,0,...,9.0,both,mid_range product,normal day,normal day,average orders,10,New Customer,6.367797,Low Spender
1,2398795,1,2,3,7,15.0,1,196,1,1,...,9.0,both,mid_range product,normal day,slowest day,average orders,10,New Customer,6.367797,Low Spender
2,473747,1,3,3,12,21.0,1,196,1,1,...,9.0,both,mid_range product,normal day,slowest day,average orders,10,New Customer,6.367797,Low Spender
3,2254736,1,4,4,7,29.0,1,196,1,1,...,9.0,both,mid_range product,slowest day,slowest day,average orders,10,New Customer,6.367797,Low Spender
4,431534,1,5,4,15,28.0,1,196,1,1,...,9.0,both,mid_range product,slowest day,slowest day,average orders,10,New Customer,6.367797,Low Spender
5,3367565,1,6,2,7,19.0,1,196,1,1,...,9.0,both,mid_range product,normal day,normal day,average orders,10,New Customer,6.367797,Low Spender
6,550135,1,7,1,9,20.0,1,196,1,1,...,9.0,both,mid_range product,normal day,busiest day,average orders,10,New Customer,6.367797,Low Spender
7,3108588,1,8,1,14,14.0,1,196,2,1,...,9.0,both,mid_range product,normal day,busiest day,average orders,10,New Customer,6.367797,Low Spender
8,2295261,1,9,1,16,0.0,1,196,4,1,...,9.0,both,mid_range product,normal day,busiest day,average orders,10,New Customer,6.367797,Low Spender
9,2550362,1,10,4,8,30.0,1,196,1,1,...,9.0,both,mid_range product,slowest day,slowest day,average orders,10,New Customer,6.367797,Low Spender
10,2968173,15,15,1,9,7.0,1,196,2,0,...,9.0,both,mid_range product,normal day,busiest day,average orders,22,Regular Customer,3.980556,Low Spender
11,1870022,15,17,2,16,8.0,1,196,6,1,...,9.0,both,mid_range product,normal day,normal day,average orders,22,Regular Customer,3.980556,Low Spender
12,1911383,15,18,2,11,7.0,1,196,1,1,...,9.0,both,mid_range product,normal day,normal day,most orders,22,Regular Customer,3.980556,Low Spender
13,2715276,15,21,1,9,7.0,1,196,1,1,...,9.0,both,mid_range product,normal day,busiest day,average orders,22,Regular Customer,3.980556,Low Spender
14,487368,15,22,1,10,14.0,1,196,1,1,...,9.0,both,mid_range product,normal day,busiest day,most orders,22,Regular Customer,3.980556,Low Spender
15,2293453,19,2,5,14,6.0,1,196,3,0,...,9.0,both,mid_range product,normal day,normal day,average orders,9,New Customer,8.372059,Low Spender
16,1973799,19,5,6,12,8.0,1,196,15,1,...,9.0,both,mid_range product,normal day,normal day,average orders,9,New Customer,8.372059,Low Spender
17,532817,19,7,4,17,6.0,1,196,1,1,...,9.0,both,mid_range product,slowest day,slowest day,average orders,9,New Customer,8.372059,Low Spender
18,1573906,21,10,3,10,6.0,1,196,2,0,...,9.0,both,mid_range product,normal day,slowest day,most orders,33,Regular Customer,7.012683,Low Spender
19,1593000,31,10,3,8,7.0,1,196,17,0,...,9.0,both,mid_range product,normal day,slowest day,average orders,20,Regular Customer,8.137793,Low Spender
20,2231262,31,17,3,11,8.0,1,196,14,1,...,9.0,both,mid_range product,normal day,slowest day,most orders,20,Regular Customer,8.137793,Low Spender
21,2580647,43,6,4,16,4.0,1,196,9,0,...,9.0,both,mid_range product,slowest day,slowest day,average orders,11,Regular Customer,7.444898,Low Spender
22,2187180,43,9,4,12,3.0,1,196,1,1,...,9.0,both,mid_range product,slowest day,slowest day,average orders,11,Regular Customer,7.444898,Low Spender
23,2497897,52,1,1,9,NaN,0,196,4,0,...,9.0,both,mid_range product,normal day,busiest day,average orders,27,Regular Customer,6.356287,Low Spender
24,1318871,52,2,1,10,7.0,1,196,5,1,...,9.0,both,mid_range product,normal day,busiest day,most orders,27,Regular Customer,6.356287,Low Spender
25,1261384,52,3,1,10,7.0,1,196,3,1,...,9.0,both,mid_range product,normal day,busiest day,most orders,27,Regular Customer,6.356287,Low Spender
26,580568,52,5,2,10,8.0,1,196,6,1,...,9.0,both,mid_range product,normal day,normal day,most orders,27,Regular Customer,6.356287,Low Spender
27,2428073,52,7,2,7,8.0,1,196,5,1,...,9.0,both,mid_range product,normal day,normal day,average orders,27,Regular Customer,6.356287,Low Spender
28,342306,52,9,1,11,7.0,1,196,5,1,...,9.0,both,mid_range product,normal day,busiest day,most orders,27,Regular Customer,6.356287,Low Spender
29,1520353,52,10,2,10,8.0,1,196,4,1,...,9.0,both,mid_range product,normal day,normal day,most orders,27,Regular Customer,6.356287,Low Spender
30,2542086,52,11,2,9,7.0,1,196,3,1,...,9.0,both,mid_range product,normal day,normal day,average orders,27,Regular Customer,6.356287,Low Spender
31,944694,52,12,1,16,6.0,1,196,7,1,...,9.0,both,mid_range product,normal day,busiest day,average orders,27,Regular Customer,6.356287,Low Spender
32,1268191,52,15,2,11,8.0,1,196,3,1,...,9.0,both,mid_range product,normal day,normal day,most orders,27,Regular Customer,6.356287,Low Spender
33,1122089,52,17,2,10,6.0,1,196,4,1,...,9.0,both,mid_range product,normal day,normal day,most orders,27,Regular Customer,6.356287,Low Spender
34,1498922,52,18,2,10,14.0,1,196,6,1,...,9.0,both,mid_range product,normal day,normal day,most orders,27,Regular Customer,6.356287,Low Spender
35,180919,52,19,3,8,8.0,1,196,4,1,...,9.0,both,mid_range product,normal day,slowest day,average orders,27,Regular Customer,6.356287,Low Spender
36,2695875,52,21,5,10,30.0,1,196,1,1,...,9.0,both,mid_range product,normal day,normal day,most orders,27,Regular Customer,6.356287,Low Spender
37,3205960,67,1,3,11,NaN,0,196,1,0,...,9.0,both,mid_range product,normal day,slowest day,most orders,24,Regular Customer,7.656790,Low Spender
38,970922,67,2,1,15,5.0,1,196,2,1,...,9.0,both,mid_range product,normal day,busiest day,average orders,24,Regular Customer,7.656790,Low Spender
39,596585,67,3,1,13,7.0,1,196,2,1,...,9.0,both,mid_range product,normal day,busiest day,average orders,24,Regular Customer,7.656790,Low Spender
40,2037087,67,4,2,9,8.0,1,196,1,1,...,9.0,both,mid_range product,normal day,normal day,average orders,24,Regular Customer,7.656790,Low Spender
41,2474111,67,5,3,14,8.0,1,196,2,1,...,9.0,both,mid_range product,normal day,slowest day,average orders,24,Regular Customer,7.656790,Low Spender
42,1568481,67,6,3,12,7.0,1,196,2,1,...,9.0,both,mid_range product,normal day,slowest day,average orders,24,Regular Customer,7.656790,Low Spender
43,2048527,67,8,2,11,7.0,1,196,1,1,...,9.0,both,mid_range product,normal day,normal day,most orders,24,Regular Customer,7.656790,Low Spender
44,2389031,67,9,2,14,7.0,1,196,1,1,...,9.0,both,mid_range product,normal day,normal day,average orders,24,Regular Customer,7.656790,Low Spender
45,2378562,67,10,1,10,6.0,1,196,1,1,...,9.0,both,mid_range product,normal day,busiest day,most orders,24,Regular Customer,7.656790,Low Spender
46,1515698,67,11,1,11,7.0,1,196,1,1,...,9.0,both,mid_range product,normal day,busiest day,most orders,24,Regular Customer,7.656790,Low Spender
47,1928050,67,12,2,12,8.0,1,196,1,1,...,9.0,both,mid_range product,normal day,normal day,average orders,24,Regular Customer,7.656790,Low Spender
48,1949274,67,13,1,10,6.0,1,196,1,1,...,9.0,both,mid_range product,normal day,busiest day,most orders,24,Regular Customer,7.656790,Low Spender
49,551869,67,14,1,9,7.0,1,196,1,1,...,9.0,both,mid_range product,normal day,busiest day,average orders,24,Regular Customer,7.656790,Low Spender

In [12]:
#7
#create column with median days since prior order
#frequency flag based on median time since prior order
#   median > 20 = non frequent customers
#   median > 10 and <= 20 = regular customer
#   median <= 10 = frequent customer
ords_prods_merged['med_order_freq'] = ords_prods_merged.groupby(['user_id'])['days_since_prior_order'].transform(np.median)
ords_prods_merged.head(15)

,order_id,user_id,order_number,orders_day_of_week,order_time,days_since_prior_order,repeat_customer,product_id,add_to_cart_order,reordered,...,_merge,price_label,busiest_day,two_busiest_days,busiest_hours,max_order,loyalty_flag,avg_price,spender_flag,med_order_freq
0,2539329,1,1,2,8,NaN,0,196,1,0,...,both,mid_range product,normal day,normal day,average orders,10,New Customer,6.367797,Low Spender,20.5
1,2398795,1,2,3,7,15.0,1,196,1,1,...,both,mid_range product,normal day,slowest day,average orders,10,New Customer,6.367797,Low Spender,20.5
2,473747,1,3,3,12,21.0,1,196,1,1,...,both,mid_range product,normal day,slowest day,average orders,10,New Customer,6.367797,Low Spender,20.5
3,2254736,1,4,4,7,29.0,1,196,1,1,...,both,mid_range product,slowest day,slowest day,average orders,10,New Customer,6.367797,Low Spender,20.5
4,431534,1,5,4,15,28.0,1,196,1,1,...,both,mid_range product,slowest day,slowest day,average orders,10,New Customer,6.367797,Low Spender,20.5
5,3367565,1,6,2,7,19.0,1,196,1,1,...,both,mid_range product,normal day,normal day,average orders,10,New Customer,6.367797,Low Spender,20.5
6,550135,1,7,1,9,20.0,1,196,1,1,...,both,mid_range product,normal day,busiest day,average orders,10,New Customer,6.367797,Low Spender,20.5
7,3108588,1,8,1,14,14.0,1,196,2,1,...,both,mid_range product,normal day,busiest day,average orders,10,New Customer,6.367797,Low Spender,20.5
8,2295261,1,9,1,16,0.0,1,196,4,1,...,both,mid_range product,normal day,busiest day,average orders,10,New Customer,6.367797,Low Spender,20.5
9,2550362,1,10,4,8,30.0,1,196,1,1,...,both,mid_range product,slowest day,slowest day,average orders,10,New Customer,6.367797,Low Spender,20.5
10,2968173,15,15,1,9,7.0,1,196,2,0,...,both,mid_range product,normal day,busiest day,average orders,22,Regular Customer,3.980556,Low Spender,10.0
11,1870022,15,17,2,16,8.0,1,196,6,1,...,both,mid_range product,normal day,normal day,average orders,22,Regular Customer,3.980556,Low Spender,10.0
12,1911383,15,18,2,11,7.0,1,196,1,1,...,both,mid_range product,normal day,normal day,most orders,22,Regular Customer,3.980556,Low Spender,10.0
13,2715276,15,21,1,9,7.0,1,196,1,1,...,both,mid_range product,normal day,busiest day,average orders,22,Regular Customer,3.980556,Low Spender,10.0
14,487368,15,22,1,10,14.0,1,196,1,1,...,both,mid_range product,normal day,busiest day,most orders,22,Regular Customer,3.980556,Low Spender,10.0

In [13]:
#7 cont.
ords_prods_merged.loc[ords_prods_merged['med_order_freq'] > 20, 'freq_flag'] = 'Nonfrequent Customer'
ords_prods_merged.loc[ (ords_prods_merged['med_order_freq'] <=20) & (ords_prods_merged['med_order_freq'] > 10), 'freq_flag'] = 'Regular Customer'
ords_prods_merged.loc[ords_prods_merged['med_order_freq'] <= 10, 'freq_flag'] = 'Frequent Customer'
ords_prods_merged['freq_flag'].value_counts(dropna = False)

Frequent Customer       21559853
Regular Customer         7208564
Nonfrequent Customer     3636437
NaN                            5
Name: freq_flag, dtype: int64

In [14]:
ords_prods_merged.head(50)

,order_id,user_id,order_number,orders_day_of_week,order_time,days_since_prior_order,repeat_customer,product_id,add_to_cart_order,reordered,...,price_label,busiest_day,two_busiest_days,busiest_hours,max_order,loyalty_flag,avg_price,spender_flag,med_order_freq,freq_flag
0,2539329,1,1,2,8,NaN,0,196,1,0,...,mid_range product,normal day,normal day,average orders,10,New Customer,6.367797,Low Spender,20.5,Nonfrequent Customer
1,2398795,1,2,3,7,15.0,1,196,1,1,...,mid_range product,normal day,slowest day,average orders,10,New Customer,6.367797,Low Spender,20.5,Nonfrequent Customer
2,473747,1,3,3,12,21.0,1,196,1,1,...,mid_range product,normal day,slowest day,average orders,10,New Customer,6.367797,Low Spender,20.5,Nonfrequent Customer
3,2254736,1,4,4,7,29.0,1,196,1,1,...,mid_range product,slowest day,slowest day,average orders,10,New Customer,6.367797,Low Spender,20.5,Nonfrequent Customer
4,431534,1,5,4,15,28.0,1,196,1,1,...,mid_range product,slowest day,slowest day,average orders,10,New Customer,6.367797,Low Spender,20.5,Nonfrequent Customer
5,3367565,1,6,2,7,19.0,1,196,1,1,...,mid_range product,normal day,normal day,average orders,10,New Customer,6.367797,Low Spender,20.5,Nonfrequent Customer
6,550135,1,7,1,9,20.0,1,196,1,1,...,mid_range product,normal day,busiest day,average orders,10,New Customer,6.367797,Low Spender,20.5,Nonfrequent Customer
7,3108588,1,8,1,14,14.0,1,196,2,1,...,mid_range product,normal day,busiest day,average orders,10,New Customer,6.367797,Low Spender,20.5,Nonfrequent Customer
8,2295261,1,9,1,16,0.0,1,196,4,1,...,mid_range product,normal day,busiest day,average orders,10,New Customer,6.367797,Low Spender,20.5,Nonfrequent Customer
9,2550362,1,10,4,8,30.0,1,196,1,1,...,mid_range product,slowest day,slowest day,average orders,10,New Customer,6.367797,Low Spender,20.5,Nonfrequent Customer
10,2968173,15,15,1,9,7.0,1,196,2,0,...,mid_range product,normal day,busiest day,average orders,22,Regular Customer,3.980556,Low Spender,10.0,Frequent Customer
11,1870022,15,17,2,16,8.0,1,196,6,1,...,mid_range product,normal day,normal day,average orders,22,Regular Customer,3.980556,Low Spender,10.0,Frequent Customer
12,1911383,15,18,2,11,7.0,1,196,1,1,...,mid_range product,normal day,normal day,most orders,22,Regular Customer,3.980556,Low Spender,10.0,Frequent Customer
13,2715276,15,21,1,9,7.0,1,196,1,1,...,mid_range product,normal day,busiest day,average orders,22,Regular Customer,3.980556,Low Spender,10.0,Frequent Customer
14,487368,15,22,1,10,14.0,1,196,1,1,...,mid_range product,normal day,busiest day,most orders,22,Regular Customer,3.980556,Low Spender,10.0,Frequent Customer
15,2293453,19,2,5,14,6.0,1,196,3,0,...,mid_range product,normal day,normal day,average orders,9,New Customer,8.372059,Low Spender,6.0,Frequent Customer
16,1973799,19,5,6,12,8.0,1,196,15,1,...,mid_range product,normal day,normal day,average orders,9,New Customer,8.372059,Low Spender,6.0,Frequent Customer
17,532817,19,7,4,17,6.0,1,196,1,1,...,mid_range product,slowest day,slowest day,average orders,9,New Customer,8.372059,Low Spender,6.0,Frequent Customer
18,1573906,21,10,3,10,6.0,1,196,2,0,...,mid_range product,normal day,slowest day,most orders,33,Regular Customer,7.012683,Low Spender,7.5,Frequent Customer
19,1593000,31,10,3,8,7.0,1,196,17,0,...,mid_range product,normal day,slowest day,average orders,20,Regular Customer,8.137793,Low Spender,6.0,Frequent Customer
20,2231262,31,17,3,11,8.0,1,196,14,1,...,mid_range product,normal day,slowest day,most orders,20,Regular Customer,8.137793,Low Spender,6.0,Frequent Customer
21,2580647,43,6,4,16,4.0,1,196,9,0,...,mid_range product,slowest day,slowest day,average orders,11,Regular Customer,7.444898,Low Spender,10.0,Frequent Customer
22,2187180,43,9,4,12,3.0,1,196,1,1,...,mid_range product,slowest day,slowest day,average orders,11,Regular Customer,7.444898,Low Spender,10.0,Frequent Customer
23,2497897,52,1,1,9,NaN,0,196,4,0,...,mid_range product,normal day,busiest day,average orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent Customer
24,1318871,52,2,1,10,7.0,1,196,5,1,...,mid_range product,normal day,busiest day,most orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent Customer
25,1261384,52,3,1,10,7.0,1,196,3,1,...,mid_range product,normal day,busiest day,most orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent Customer
26,580568,52,5,2,10,8.0,1,196,6,1,...,mid_range product,normal day,normal day,most orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent Customer
27,2428073,52,7,2,7,8.0,1,196,5,1,...,mid_range product,normal day,normal day,average orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent Customer
28,342306,52,9,1,11,7.0,1,196,5,1,...,mid_range product,normal day,busiest day,most orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent Customer
29,1520353,52,10,2,10,8.0,1,196,4,1,...,mid_range product,normal day,normal day,most orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent Customer
30,2542086,52,11,2,9,7.0,1,196,3,1,...,mid_range product,normal day,normal day,average orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent Customer
31,944694,52,12,1,16,6.0,1,196,7,1,...,mid_range product,normal day,busiest day,average orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent Customer
32,1268191,52,15,2,11,8.0,1,196,3,1,...,mid_range product,normal day,normal day,most orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent Customer
33,1122089,52,17,2,10,6.0,1,196,4,1,...,mid_range product,normal day,normal day,most orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent Customer
34,1498922,52,18,2,10,14.0,1,196,6,1,...,mid_range product,normal day,normal day,most orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent Customer
35,180919,52,19,3,8,8.0,1,196,4,1,...,mid_range product,normal day,slowest day,average orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent Customer
36,2695875,52,21,5,10,30.0,1,196,1,1,...,mid_range product,normal day,normal day,most orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent Customer
37,3205960,67,1,3,11,NaN,0,196,1,0,...,mid_range product,normal day,slowest day,most orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent Customer
38,970922,67,2,1,15,5.0,1,196,2,1,...,mid_range product,normal day,busiest day,average orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent Customer
39,596585,67,3,1,13,7.0,1,196,2,1,...,mid_range product,normal day,busiest day,average orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent Customer
40,2037087,67,4,2,9,8.0,1,196,1,1,...,mid_range product,normal day,normal day,average orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent Customer
41,2474111,67,5,3,14,8.0,1,196,2,1,...,mid_range product,normal day,slowest day,average orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent Customer
42,1568481,67,6,3,12,7.0,1,196,2,1,...,mid_range product,normal day,slowest day,average orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent Customer
43,2048527,67,8,2,11,7.0,1,196,1,1,...,mid_range product,normal day,normal day,most orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent Customer
44,2389031,67,9,2,14,7.0,1,196,1,1,...,mid_range product,normal day,normal day,average orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent Customer
45,2378562,67,10,1,10,6.0,1,196,1,1,...,mid_range product,normal day,busiest day,most orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent Customer
46,1515698,67,11,1,11,7.0,1,196,1,1,...,mid_range product,normal day,busiest day,most orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent Customer
47,1928050,67,12,2,12,8.0,1,196,1,1,...,mid_range product,normal day,normal day,average orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent Customer
48,1949274,67,13,1,10,6.0,1,196,1,1,...,mid_range product,normal day,busiest day,most orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent Customer
49,551869,67,14,1,9,7.0,1,196,1,1,...,mid_range product,normal day,busiest day,average orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent Customer

In [15]:
#9 export
ords_prods_merged.to_pickle(os.path.join(path, 'NewDataSets', 'orders_products_combined.pkl'))